### ISSUE TITLE
"Edit Global Stylesheet" doesn't open

### ISSUE THREAD

**Issue by raingart** [BrassStack/stylebot#3]

**Comment by konradw-dev** [comment]
Hi @raingart ,

I am closing this issue in favor of the original [ankit/stylebot](https://github.com/ankit/stylebot) extension, which has resumed development.  I am retiring Stylebot Lite since it has served its purpose.  If you are still experiencing this issue in the latest version there, I would encourage you to submit there as well.

I'm glad you found Stylebot Lite useful!

-Konrad
