### ISSUE TITLE
Remove listing for Stylebot Lite

### ISSUE THREAD

**Issue by ankit** [BrassStack/stylebot#4]
@Icebird This is to request you to remove the Chrome listing for Stylebot Lite (https://chrome.google.com/webstore/detail/stylebot-lite/lkcdgdbfbbnpnljlalmcjnepgjnmgigh?hl=en-US)

I am now actively maintaining https://github.com/ankit/stylebot (with a much newer version) and I would like to avoid confusion since we are not actively maintaining this version...

I have hopefully fixed the original bugs that prompted this fork...But I welcome any suggestions / contributions to make the original better!

**Comment by konradw-dev** [comment]
Hi @ankit , 

Thanks for resuming this project!  I'd be happy to take a look at your updates and see if it meets all of my needs now.  If so, I don't see any reason to continue listing my fork.  Other than the rule order bugfix, the two main features I needed were:

1. Provide a way to quickly toggle custom CSS on and off for the current page, for previewing, screenshots, documentation etc.
2. A Cancel button on the Stylebot custom CSS "Code" view (or all three views) to abandon custom CSS changes made there since opening it.

In your version 3.0.6 I see toggles on the quick menu for site styles, but they don't seem to work for me.  When I click them, nothing happens.

If you can provide for these two items, I would be more than happy to unlist my fork.

Thanks!
-Icebird

**Comment by konradw-dev** [comment]
Hi @ankit ,

After uninstalling your version 3.0.6, restarting Chrome, and then re-installing it again, the toggles now work for me.  I noticed a few odd behaviors I may report in your issues section and would still like a "cancel" button on the Code view, but I am willing to unlist Stylebot Lite now as I think you have addressed my main concerns.

-Konrad

**Comment by ankit** [comment]
@Icebird Thanks! Yes, please help report issues in the main repo
